name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/vest-build-dotnet/
    permissions:
      id-token: write
    steps:
      - name: Checkout vest-build-dotnet
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.18"

      - name: Install Python
        run: uv python install

      - name: Check that uv.lock is up to date
        run: uv lock --check

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
